name: Docker Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Declare commit sha to use on other actions
        id: vars
        shell: bash
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"  

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USER }}
          PASSWORD: ${{ secrets.DOCKER_KEY }}
          DOCKERFILE: "Dockerfile.artifact"
          IMAGE_NAME: "smileproject/smilepy3action"
          TAG_NAME: ${{ steps.vars.outputs.sha_short }}
          LATEST: "true"
